### PR TITLE
Full release with ODK v1.4.1

### PR DESCRIPTION
**Pull request by jseager7**
@matentzn Currently the full release is not working due to timeout issues with ChEBI.

Previous discussion is here: https://github.com/INCATools/ontology-development-kit/issues/884

### CODE REVIEW

**Review by matentzn — COMMENTED** [review]
I dont see changes to your `Makefile`.

You run `sh run.sh make update_repo` after making any change to src/ontology/phipo-odk.yaml

**Comment by jseager7** [comment]
@matentzn I've updated the Makefile with `update_repo` and prepared a release with the slim version of ChEBI on this branch. I didn't see any errors reported in the console so I'm assuming everything went okay.

If everything looks okay to you, I'll merge this PR and tag the release. If you don't get a chance to respond today then I'll remake the release later.

**Comment by jseager7** [comment]
Whoops, didn't notice the merge conflicts. That's due to a partial release I did earlier so we could use the latest terms with another tool. I'll fix that.

**Comment by jseager7** [comment]
I'm a bit concerned about the size of the commit: 734,712 insertions and 1,307,936 deletions! Are there files that aren't being ignored that should be? Or is this just because we haven't updated the imports in a long time?

**Comment by matentzn** [comment]
There was a major update to our serialisers in version 1.4 Just spot check some changes in see if they are mostly related to  xsd :string

**Comment by jseager7** [comment]
> Just spot check some changes in see if they are mostly related to xsd :string

I think that explains the changes in the PHIPO release files, thanks. The import files also seem to have changed from RDF/XML syntax to Functional Syntax, which accounts for the really massive diff on some files.

**Comment by matentzn** [comment]
Yes thats right! A one time large diff is expected. I would recommend doing that release today, and make another one soon, and double check then that the diff looks sane.

**Review by matentzn — APPROVED** [review]
Looks good to me!

**Comment by matentzn** [comment]
This is not in any OBO guidelines, but you must tag the commit that contains all the changes. If you did a merge commit, the other commits will have been removed, so you have to tag the merge commit!

**Pull request merged**
